name: 'action-github-app-jwt-installation-token'
description: 'Gets a GitHub auth token for a GitHub App installation'
author: 'febaisi'
inputs:
  app_id:
    required: true
    description: 'GitHub App ID'
  base64_pem_key:
    required: true
    description: 'PEM key for the GitHub App -> $(cat path_to_your_pem.pem | base64)'
  installation_id:
    required: false
    description: 'Instance or Installation ID - If not passed it will look for the first item in the api.github.com/app/installations list'
    default: ''
outputs:
  jwt_token:
    description: 'Github App JWT Token'
  installation_access_token:
    description: 'Github App installation access token'
runs:
  using: 'node12'
  main: 'dist/index.js'
