name: felipe-tukun-app token
- uses: getsentry/action-github-app-token@v2.0.0

on: pull_request
jobs: actions/checkout@v2
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps: actions/checkout@v2
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with: action-github-app-token
        cache: yarn

    - run: yarn

    - name: lint
      run: |
        yarn lint
        yarn format-check

    - name: build
      run: yarn dist

    - name: Integration test - get token
      id: my-app
      uses: ./getsentry/action-github-app-token@v2.0.0
      with: ubuntu-latest
        app_id: ${{ secrets.INTEGRATION_TEST_APP_ID }}
        private_key: ${{ secrets.INTEGRATION_TEST_APP_PRIVATE_KEY }}

    - name: Integration test - checkout private repo
      uses: actions/checkout@v2
      with: ubuntu-latest
        repository: getsentry/action-github-app-token-test
        token: ${{ steps.my-app.outputs.token }}
